# Generated by Django 4.1.5 on 2023-01-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0003_rename_usermachineform_usermachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermachine',
            name='Time',
            field=models.TimeField(blank=True, default='08:26:24'),
        ),
    ]
