# Generated by Django 4.1.5 on 2023-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0004_usermachine_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kein_Maschine', models.BigIntegerField(default=0)),
                ('Pronto', models.BigIntegerField(default=0)),
                ('Cruiser', models.BigIntegerField(default=0)),
                ('Lemken_Smaragt', models.BigIntegerField(default=0)),
                ('Komoststreuer', models.BigIntegerField(default=0)),
                ('Anhanger', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Time',
            field=models.TimeField(blank=True, default='11:31:33'),
        ),
    ]
