# Generated by Django 4.1.5 on 2023-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0005_machines_alter_usermachine_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermachine',
            name='MaschineLastRecord',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='SchlepperLastRecord',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Time',
            field=models.TimeField(blank=True, default='16:15:44'),
        ),
    ]
