# Generated by Django 4.1.5 on 2023-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0006_usermachine_maschinelastrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='Date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
