# Generated by Django 4.1.5 on 2023-01-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0007_alter_usermachine_date_alter_usermachine_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='Date',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Time',
            field=models.CharField(blank=True, default=None, max_length=24),
        ),
    ]
