# Generated by Django 4.1.5 on 2023-02-04 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RGForm', '0009_schlepper_machines_lastupdateby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermachine',
            name='Einheit',
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Date',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='LiterDiesel',
            field=models.CharField(default='Kein Schleper', max_length=150, verbose_name='Liter Diesel'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='OrtDerTankung',
            field=models.CharField(choices=[('None', '-----'), ('Halle', 'Halle'), ('Eigen', 'Eigen')], default='None', max_length=24, verbose_name='Ort der Tankung'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Schlepper',
            field=models.CharField(choices=[('None', '-----'), ('Kein Schleper', 'Kein Schleper'), ('6155R Stunden', '6155R Stunden'), ('6215R Stunden', '6215R Stunden')], default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Taetigkeit',
            field=models.CharField(choices=[('None', '-----'), ('neu', 'neu'), ('Pressen', 'Pressen'), ('Zubringer', 'Zubringer'), ('Säen', 'Säen'), ('Grubbern', 'Grubbern')], default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='User',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
