# Generated by Django 4.1.5 on 2023-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0010_remove_usermachine_einheit_alter_usermachine_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermachine',
            name='Time',
        ),
        migrations.AddField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Date',
            field=models.CharField(default=None, max_length=24, verbose_name='Datum'),
        ),
    ]
