# Generated by Django 4.1.5 on 2023-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0011_remove_usermachine_time_usermachine_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='4-2-2023 16:14:18', max_length=60),
        ),
    ]
