# Generated by Django 4.1.5 on 2023-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0012_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermachine',
            name='MaschineUnit',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='SchlepperUnit',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='05-02-2023 10:50:34', max_length=60, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='LiterDiesel',
            field=models.CharField(default='None', max_length=100, verbose_name='Liter Diesel'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Maschine',
            field=models.CharField(choices=[('None', '-----'), ('Kein Maschine', 'Kein Maschine'), ('Pronto', 'Pronto'), ('Cruiser', 'Cruiser'), ('Tiger', 'Tiger'), ('Lemken Smaragt', 'Lemken Smaragt'), ('Komoststreuer', 'Komoststreuer'), ('Anhanger', 'Anhanger')], default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Notizen',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
