# Generated by Django 4.1.5 on 2023-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0013_usermachine_maschineunit_usermachine_schlepperunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='05-02-2023 11:31:45', max_length=60, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Notizen',
            field=models.TextField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Schlepper',
            field=models.CharField(choices=[('None', '-----'), ('Kein Schleper', 'Kein Schleper'), ('6155R Stunden', '6155R'), ('6215R Stunden', '6215R')], default='None', max_length=24),
        ),
    ]
