# Generated by Django 4.1.5 on 2023-02-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0015_rename_date_usermachine_datum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermachine',
            old_name='Datum',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='usermachine',
            old_name='MaschineEinheit',
            new_name='MaschineUnit',
        ),
        migrations.RenameField(
            model_name='usermachine',
            old_name='SchlepperEinheit',
            new_name='SchlepperUnit',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='MaschineAnfang',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='MaschineAnfangEndeZuletzt',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='MaschineVerbrauch',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='SchlepperAnfang',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='SchlepperAnfangEndeZuletzt',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='SchlepperVerbrauch',
        ),
        migrations.RemoveField(
            model_name='usermachine',
            name='ZeitstempelDerEingabe',
        ),
        migrations.AddField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='05-02-2023 13:23:04', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='MaschineAnzahl',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='MaschineLastRecord',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='MaschineStart',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='SchlepperAnzahl',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='SchlepperLastRecord',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AddField(
            model_name='usermachine',
            name='SchlepperStart',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='MaschineEnde',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='SchlepperEnde',
            field=models.CharField(default='None', max_length=150, verbose_name='System ZeitstempelDerEingabe'),
        ),
    ]
