# Generated by Django 4.1.5 on 2023-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0016_rename_datum_usermachine_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='05-02-2023 13:25:32', max_length=60, verbose_name='System ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='MaschineEnde',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='MaschineLastRecord',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='MaschineStart',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='SchlepperAnzahl',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='SchlepperEnde',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='SchlepperLastRecord',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='SchlepperStart',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
