# Generated by Django 4.1.5 on 2023-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0019_machines_tiger_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='05-02-2023 15:49:06', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
