# Generated by Django 4.1.5 on 2023-02-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0021_dropdownmenu_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownmenu',
            name='dropDownName',
        ),
        migrations.AddField(
            model_name='dropdownmenu',
            name='drop_down_name',
            field=models.CharField(default='None', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Auftragsgeber',
            field=models.CharField(choices=[(None, '------'), ('Horsch', 'Horsch'), ('Maschinenring', 'Maschinenring'), ('Schmidl', 'Schmidl'), ('Zilch', 'Zilch'), ('Dirmeier', 'Dirmeier')], default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='09-02-2023 21:02:35', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
