# Generated by Django 4.1.5 on 2023-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0024_unittable_alter_dropdownmenu_drop_down_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='Anhanger',
            new_name='Anhänger',
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='11-02-2023 17:41:23', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
