# Generated by Django 4.1.5 on 2023-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0025_rename_anhanger_machines_anhänger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermachine',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='12-02-2023 13:15:15', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
