# Generated by Django 4.1.5 on 2023-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0026_usermachine_created_at_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schlepper',
            old_name='Studen_6215R',
            new_name='SAD_SI_185',
        ),
        migrations.RenameField(
            model_name='schlepper',
            old_name='Stunden_6155R',
            new_name='SAD_SI_601',
        ),
        migrations.AddField(
            model_name='schlepper',
            name='SAD_SI_602',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='13-02-2023 17:45:36', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
