# Generated by Django 4.1.5 on 2023-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0027_rename_studen_6215r_schlepper_sad_si_185_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='13-02-2023 17:46:08', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
