# Generated by Django 4.1.5 on 2023-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0031_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schlepper',
            old_name='SAD_SI_185',
            new_name='Studen_6215R',
        ),
        migrations.RenameField(
            model_name='schlepper',
            old_name='SAD_SI_601',
            new_name='Stunden_6155R',
        ),
        migrations.RemoveField(
            model_name='schlepper',
            name='SAD_SI_602',
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='13-02-2023 19:17:23', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
