# Generated by Django 4.1.5 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0033_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='13-02-2023 19:30:46', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='LiterDiesel',
            field=models.CharField(default='0', max_length=100, verbose_name='Liter Diesel'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='OrtDerTankung',
            field=models.CharField(default='', max_length=24, verbose_name='Ort der Tankung'),
        ),
    ]
