# Generated by Django 4.1.5 on 2023-02-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0035_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='13-02-2023 19:31:02', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
