# Generated by Django 4.1.5 on 2023-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0036_alter_usermachine_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='13-02-2023 19:32:45', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Notizen',
            field=models.TextField(default='', max_length=150),
        ),
    ]
