# Generated by Django 4.1.5 on 2023-02-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RGForm', '0037_alter_usermachine_datetime_alter_usermachine_notizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='19-02-2023 14:31:38', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
        migrations.CreateModel(
            name='PasswordTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='None', max_length=100, verbose_name='password')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_name')),
            ],
        ),
    ]
