# Generated by Django 4.1.5 on 2023-02-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RGForm', '0041_remove_user_admin_remove_user_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='None', max_length=100, verbose_name='password')),
                ('driver', models.CharField(default='None', max_length=100, verbose_name='driver')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='passwordtables',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='26-02-2023 13:40:23', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
        migrations.DeleteModel(
            name='PasswordTables',
        ),
    ]
