# Generated by Django 4.1.5 on 2023-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0042_userprofile_remove_passwordtables_user_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='Anhänger',
            new_name='Keine_Maschine',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='Kein_Maschine',
            new_name='Komoststreuer_1',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='Komoststreuer',
            new_name='Komoststreuer_2',
        ),
        migrations.RenameField(
            model_name='machines',
            old_name='Lemken_Smaragt',
            new_name='Lemken_Smaragd',
        ),
        migrations.RenameField(
            model_name='schlepper',
            old_name='Studen_6215R',
            new_name='SAD_SI_185',
        ),
        migrations.RenameField(
            model_name='schlepper',
            old_name='Stunden_6155R',
            new_name='SAD_SI_601',
        ),
        migrations.AddField(
            model_name='machines',
            name='Pflug_5_Schar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machines',
            name='Presse',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schlepper',
            name='SAD_SI_602',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='04-03-2023 20:45:12', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='Taetigkeit',
            field=models.CharField(default='0', max_length=24),
        ),
    ]
