# Generated by Django 4.1.5 on 2023-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGForm', '0043_rename_anhänger_machines_keine_maschine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Cruiser',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Keine_Maschine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Komoststreuer_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Komoststreuer_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Lemken_Smaragd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Pflug_5_Schar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Presse',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Pronto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='Tiger',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schlepper',
            name='Kein_Schleper',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schlepper',
            name='SAD_SI_185',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schlepper',
            name='SAD_SI_601',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='schlepper',
            name='SAD_SI_602',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usermachine',
            name='DateTime',
            field=models.CharField(default='04-03-2023 21:10:54', max_length=60, verbose_name='ZeitstempelDerEingabe'),
        ),
    ]
